const cardOne = [{
  name: 'Multi Post Stories',
  nameTwo: 'Keeping track of hundreds of components website',
  technologies: ['html', 'Bootstrap', 'Ruby on rails'],
  image: 'images/SnapshootPortfolio.png',
  description: 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it 1960s with the releaLorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it 1960s with the releax map lapora verita.',
  liveVersion: 'see live',
  linkDemo: '#',
  repo: 'see repo',
  LinkRepo: '#',
},
{
  name: 'Moon\'s Fall-Rock Festival',
  nameTwo: 'Moon\'s Fall-Rock Festival - Capstone project',
  technologies: ['html', 'CSS', 'JavaScript'],
  image: 'images/capstone.png',
  description: 'Responsive site from mobile to desktop. It was based on Cindy Shin in Behance design. It changes in between the from screen and the about page.The concept was to simulate a promotion to a big rock concert in Japan ',
  liveVersion: 'see live',
  linkDemo: 'https://zkr024.github.io/Capstone-Project/',
  repo: 'see repo',
  LinkRepo: 'https://github.com/zkr024/Capstone-Project',
},
{
  name: 'To Do List',
  nameTwo: 'To Do List application',
  technologies: ['CSS', 'JavaScript', 'Webpack'],
  image: 'images/toDoList.png',
  description: 'Application that uses the localStorage to keep the information on the activities that are pending to be done and also those that are completed. It provides an option to edit activities and also delete them. The clear all applies to those that are marked as completed by selecting the checkbox.',
  liveVersion: 'see live',
  linkDemo: 'https://zkr024.github.io/To-Do-List/',
  repo: 'see repo',
  LinkRepo: 'https://github.com/zkr024/To-Do-List',
},
{
  name: 'Finantial Metrics',
  nameTwo: 'Finantial Metrics app',
  technologies: ['React', 'Redux', 'CSS'],
  image: 'images/financial.png',
  description: 'The application displays the last years financial records from the most important companies in the word. It is built using react and redux and it feeds from the Financial Modeling Prep API.',
  liveVersion: 'see live',
  linkDemo: 'https://peppy-tarsier-ec49cb.netlify.app/',
  repo: 'see repo',
  LinkRepo: 'https://github.com/zkr024/financial-metrics',
},
{
  name: 'Budget app',
  nameTwo: 'Budget app',
  technologies: ['Rails', 'Ruby', 'PostgreSQL'],
  image: 'images/budget.png',
  description: 'A mobile app built with rails and PostgreSQL. After signing in the user is able to add categories and see how much has been spent in each added category. Can add transactions after selecting the category that they fell under and assign more categories if needed.',
  liveVersion: 'see live',
  linkDemo: 'https://morning-oasis-24983.herokuapp.com/',
  repo: 'see repo',
  LinkRepo: 'https://github.com/zkr024/Budget-app',
},
{
  name: 'Multi Post Stories sixth project',
  nameTwo: 'Keeping track of hundreds  of components website 6',
  technologies: ['html', 'Bootstrap', 'Ruby on rails'],
  image: 'images/gym2.png',
  description: 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it 1960s with the releaLorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it 1960s with the releax map lapora verita.',
  liveVersion: 'see live',
  linkDemo: '#',
  repo: 'see repo',
  LinkRepo: '#',
},
{
  name: 'Multi Post Stories fifth project',
  nameTwo: 'Keeping track of hundreds  of components website 7',
  technologies: ['html', 'Bootstrap', 'Ruby on rails'],
  image: 'images/SnapshootPortfolio.png',
  description: 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it 1960s with the releaLorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it 1960s with the releax map lapora verita.',
  liveVersion: 'see live',
  linkDemo: '#',
  repo: 'see repo',
  LinkRepo: '#',
}];

export default cardOne;